Mom2/Models/SongModel.cs
using System.ComponentModel.DataAnnotations;

namespace Mom2.Models
{
    public class SongModel
    {
        //properties
       
        //required - if not filled in correctly
        [Required(ErrorMessage = "Please fill in Song correctly.")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Please fill in album correctly.")]
        [MinLength(2)]
        public string? Album { get; set; }
        [Required(ErrorMessage = "Please fill in artist correctly.")]
        [MinLength(2)]
        public string? Artist { get; set; }
        [Required(ErrorMessage = "Please fill in Genre correctly.")]
        public string? Genre { get; set; }
        [Display(Name = "Listened to")]
        [Required(ErrorMessage = "Please fill in listened to correctly.")]
        public string? Listened { get; set; }
        [Display(Name = "Would you listen to this song again?")]
        [Required(ErrorMessage = "Please fill in would-listen-to correctly.")]
        public bool Listen { get; set; }
        [Display(Name = "Rate this song from 1(bad) to 5(best song in the world)")]
        [Required(ErrorMessage = "Please fill in rate correctly.")]
        public int? Review { get; set; }
        [Display(Name = "Add Url from youtubes embedded code - but only the URL.")]
        public string? Url { get; set; }
    }
}

Mom2/Controllers/TildaController.cs
using Microsoft.AspNetCore.Mvc;
using Mom2.Models;
using Newtonsoft.Json;

namespace moment2.Controllers
{
    public class TildaController : Controller
    {
        private readonly ILogger<TildaController> _logger;

        public TildaController(ILogger<TildaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //sessionsvariable
            string s2 = HttpContext.Session.GetString("test");
            ViewBag.text = s2;

            return View();
        }

        //about-page
        [HttpGet("/about")]
        public IActionResult About()
        {

            //sessionvariable
            string s = "This is a text from a session.";
            HttpContext.Session.SetString("test", s);

            return View();
            
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(SongModel model)
        {
            if (ModelState.IsValid)
            {
                //lagra
                var JsonStr = System.IO.File.ReadAllText("songs.json");
                var JsonObj = JsonConvert.DeserializeObject<List<SongModel>>(JsonStr);

                if (JsonObj != null)
                {
                    JsonObj.Add(model);
                }
                //convert to json-string and save
                System.IO.File.WriteAllText("songs.json", JsonConvert.SerializeObject(JsonObj, Formatting.Indented));
                ModelState.Clear();
            }
            return View();
        }

        //songs-page
        [HttpGet("/songs")]
        public IActionResult Songs()
        {
            var JsonStr = System.IO.File.ReadAllText("songs.json");
            var JsonObj = JsonConvert.DeserializeObject<List<SongModel>>(JsonStr);

            ViewBag.Description = "Songs!";
            return View(JsonObj);
        }
    }



    }

   

Mom2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <header>
       <div class="headergrid">

           <div class="headergrids">
               <p class="headerp">Songs for you!</p>
           </div>

           <div class="headergrids2">
       
               <!--Partial for menu-->
       <partial name="~/Views/Shared/_Menu.cshtml" />

        </div>
        </div>
    </header>
    <div class="content">
        <main role="main" class="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <script src="~/js/site.js"></script>
        <p class="footerp">This page is created with ASP.NET</p>
        <p class="footerp">Copyright 2022 Tilda Källström</p>
    </footer>
   
</body>
</html>

Mom2/Views/Shared/_Menu.cshtml
<div class="mobile">
        <div class="ham" id="hamburger" onclick="hamburgermenu(this)">
          <div class="lineone"></div>
          <div class="linetwo"></div>
          <div class="linethree"></div>
        </div> 
       <!-- mobilmenyns navigering -->
         </div> 
     
            <nav class="navbar">
                  <ul>
                         <li class="nav-item">
                              <a class="" asp-controller="Tilda" asp-action="Index">Home</a>
                         </li>
                          <li class="nav-item">
                            <a class="" asp-controller="Tilda" asp-action="About">About</a>
                        </li>
                          <li class="nav-item">
                            <a class="" asp-controller="Tilda" asp-action="Add">Add song</a>
                        </li>
                        <li class="nav-item">
                            <a class="" asp-controller="Tilda" asp-action="Songs">View songs</a>
                        </li>
         
                   </ul>
             </nav>

Mom2/Views/Shared/_Time.cshtml
                <!--date and date to string to only show date, not time-->
                @{
                    var date = DateTime.Now;
                }
                <div class="time">
                <p>@date.ToString("yyyy/MM/dd")<br />
                <!--Show only time, not date-->
                 @date.ToString("HH:m")</p>
                </div>
          

Mom2/Views/Tilda/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "_Layout";

}

<h1>About</h1>

<p>Add your favourite songs to this website!</p><br />
<p>In the add songs page you can add all your favourites, and you can see the added
    songs in the view songs page.
</p><br />

<p>This website is created with ASP.NET for the course .NET at Mid Sweden University 2022 by Tilda Källström.</p><br />
<p>The website is not real, but the music are.</p><br />


      <div class="gride2">
            <div class="user">
                <h3>-Best app in the world!</h3>
                <span class="users">Amanda Heisenberg from Colorado</span>
            </div>

            <div class="user">
                <h3>-I found my favourite bands here!</h3>
                <span class="users">Tommi Sparrow from Texas</span>
            </div>

            <div class="user">
                <h3>-My band made it to the app!</h3>
                <span class="users">Elias Pepper from Albania</span>
            </div>
        </div>




        <partial name="~/Views/Shared/_Time.cshtml" />

Mom2/Views/Tilda/Add.cshtml
@model Mom2.Models.SongModel
@{
    ViewData["Title"] = "Add song";
}

<h1>Add song</h1>
<p>On this page you can add a new song to list of awesome songs!</p>
<h2>Fill in:</h2> 
<ul class="centerul">
    <li>the name of the song</li>
    <li>which album the song is in</li>
    <li>the artist who made the song</li>
    <li>which genre the song belongs to</li>
    <li>when you listened to it</li>
    <li>if you would listen to it again</li>
    <li>how many stars you want to give the song</li>
    <li>the url of the song</li>
</ul><br />

<form method="post" class="form">
    <div asp-validation-summary="ModelOnly"></div>
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span><br /><br />
    <label asp-for="Album"></label>
    <input asp-for="Album" />
    <span asp-validation-for="Album"></span><br /><br />
    <label asp-for="Artist"></label>
    <input asp-for="Artist" />
    <span asp-validation-for="Artist"></span><br /><br />
    <label asp-for="Genre"></label>
    <select asp-for="Genre">
        <option value="Pop">Pop</option>
        <option value="Punk">Punk</option>
        <option value="Rock">Rock</option>
        <option value="Electronic">Electronic</option>
        <option value="Post-punk">Post-punk</option>
    </select><br /><br />
     <label asp-for="Listened"></label>
    <input type="date" asp-for="Listened" /><br /><br />
      <label asp-for="Listen"></label>
    <input type="checkbox" asp-for="Listen" /><br /><br /><br />
      <label asp-for="Review"></label>
    <select asp-for="Review">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select><br /><br />
     <label asp-for="Url"></label>
    <input asp-for="Url" />
    <input type="submit" value="Add song" />
</form>

Mom2/Views/Tilda/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}

<h1 class="homeh1">Songs for you!</h1>
<p>This is the website for all the music-lovers in the world.</p>
<p>On this page we let you upload and rate your favourite songs for everyone to see.</p><br />
<p>We are currently listing the best songs in the following genres:</p>
<ul class="ulindex">
    <li class="red">Pop</li>
    <li class="orange">Rock</li>
    <li class="green">Electronic</li>
    <li class="blue">Punk</li>
    <li class="purple">Post-punk</li>
</ul>
<p>If you like other genres, we'll to bad for you!</p>
<div class="gridindex">
 <div class="center1">
          <button class="button" onclick="window.location.href='Tilda/Add'">Add song >></button>
        </div>

        <div class="center1">
          <button class="button" onclick="window.location.href='Songs'">View songs >></button>
        </div>

        </div>
        <img class="frontimg" src="~/logo.png">


        <div class="gride">
            <div class="user">
                <h3>-Best app in the world!</h3>
                <span class="users">Amanda Heisenberg from Colorado</span>
            </div>

            <div class="user">
                <h3>-I found my favourite bands here!</h3>
                <span class="users">Tommi Sparrow from Texas</span>
            </div>

            <div class="user">
                <h3>-My band made it to the app!</h3>
                <span class="users">Elias Pepper from Albania</span>
            </div>
        </div>




        <div class="bottom">
            <div>
<p class="down">.....Pssssst, Visit the About-page, and then come back here to see the session-magic.</p>
<p class="session">@ViewBag.text</p>
</div>

<!--Partial to show time-->
<partial name="~/Views/Shared/_Time.cshtml" />

</div>

Mom2/Views/Tilda/Songs.cshtml
@model List<Mom2.Models.SongModel>

@{
    ViewData["Title"] = "View songs";
}

<h1>@ViewBag.Description</h1>


    <div class="grids">
         @if(Model != null)
    {
        @foreach(var song in Model)
        {
        <div class="song">
<span class="songname">@song.Name</span><br> <span>A song made by the</span> 
 
                @if(@song.Genre == "Pop") {
                   <span class="red">@song.Genre</span> 
                } 
                @if(@song.Genre == "Rock") {
                   <span class="orange">@song.Genre</span>  
                }
                @if(@song.Genre == "Electronic") {
                   <span class="green">@song.Genre</span>  
                }
                @if(@song.Genre == "Punk") {
                   <span class="blue">@song.Genre</span>  
                }
                @if(@song.Genre == "Post-punk") {
                   <span class="purple">@song.Genre</span>  
                }




<span>band</span> <span class="artist">@song.Artist</span> <span>in the @song.Album album got </span>

@if(song.Review == 1) {
<span class="review1">@song.Review</span>
    }
    @if(song.Review == 2) {
<span class="review2">@song.Review</span> 
    }
    @if(song.Review == 3) {
<span class="review3">@song.Review</span>
    }
    @if(song.Review == 4) {
<span class="review4">@song.Review</span>
    }
    @if(song.Review == 5) {
<span class="review5">@song.Review</span>
    }

    <span>stars and</span> 

              @if(@song.Listen) {
                   <span class="would">we would listen to it again!</span>
                } else {
                   <span class="wouldnt">we don't want to hear this song anymore.</span>
                }
            <br> <iframe class='video' src='@song.Url' title='YouTube video player' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>
         
        </div>
         }
    }
    </div>